# Generated by Django 3.2 on 2022-05-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='endpoint',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='record',
            name='startpoint',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
    ]
