# Generated by Django 3.2 on 2022-05-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220511_1936'),
        ('records', '0002_auto_20220505_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='projects.project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='SubRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startpoint', models.DateTimeField(verbose_name='Начало')),
                ('endpoint', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrecords', to='records.record', verbose_name='Таймер')),
            ],
            options={
                'verbose_name': 'Подзапись',
                'verbose_name_plural': 'Подзаписи',
            },
        ),
    ]
