# Generated by Django 3.2 on 2022-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0004_auto_20220518_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='avg_longitude',
            field=models.IntegerField(default=0, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='record',
            name='endpoint',
            field=models.DateTimeField(blank=True, default=None, verbose_name='конец работы'),
        ),
        migrations.AddField(
            model_name='record',
            name='startpoint',
            field=models.DateTimeField(blank=True, default=None, verbose_name='начало работы впервые'),
        ),
    ]
