# Generated by Django 3.2 on 2022-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0007_auto_20220521_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='endpoint',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='record',
            name='startpoint',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало работы впервые'),
        ),
    ]
