# Generated by Django 3.2 on 2022-05-21 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0008_auto_20220521_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='avg_longitude',
        ),
        migrations.RemoveField(
            model_name='record',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='record',
            name='startpoint',
        ),
    ]
