# Generated by Django 3.2 on 2022-05-22 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('records', '0010_subrecord_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrecord',
            options={'ordering': ['-endpoint'], 'verbose_name': 'Подзапись', 'verbose_name_plural': 'Подзаписи'},
        ),
    ]
