# Generated by Django 3.2 on 2022-05-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220511_1936'),
        ('records', '0011_alter_subrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='projects.project', verbose_name='Проект'),
        ),
    ]
